### ISSUE TITLE
Decide on a Hugo Theme

### ISSUE THREAD

**Issue by actuarialvoodoo** [institute-and-faculty-of-actuaries/mlr-blog#1]

**Comment by actuarialvoodoo** [comment]
You can view hugo blog themes at [https://themes.gohugo.io/tags/blog/](https://themes.gohugo.io/tags/blog/)

A couple that I like are:

- [Academic](https://themes.gohugo.io/academic/)
- [Universal](https://github.com/devcows/hugo-universal-theme)

**Comment by grainnemcguire** [comment]
Thanks for doing this.

My vote is for Academic. It's quite easy to use, has projects which would be good for different work streams, featured posts and looks clean.

I set up my own webpage with it last month - https://grainnemcguire.github.io/ if you're interested. I did consider universal at the same time, but I liked the clean but professional look of academic.

**Comment by JackyP** [comment]
My thanks as well.

From earlier discussions, it seemed like Academic was the way to go. It met all our requirements and looks clean.
